### PR TITLE
added the ability to not revoke refresh tokens until a access token

### PR DESCRIPTION
**Pull request by rsharrott**
created with the refresh token has been used at least once

### CODE REVIEW

**Comment by moneytree-doug** [comment]
If you make a PR to doorkeeper, you should use this PR since it talks about it: https://github.com/doorkeeper-gem/doorkeeper/issues/449

**Comment by moneytree-doug** [comment]
Is this CI supposed to work?

**Comment by rsharrott** [comment]
In theory yes, the CI should pass but it is failing on rails versions and ORMs we don't use

**Comment by rafaelsales** [comment]
@rsharrott  was this ever merged to Doorkeeper?

**Comment by moneytree-doug** [comment]
@rafaelsales No, it hasn't, but other members of the community have picked it up and attempted to get it merged. If you follow the long trail, you would end up here: https://github.com/doorkeeper-gem/doorkeeper/pull/769

**Pull request merged**
